<div style="background:#f8f8f8; border-top:1px solid #e3e3e3;border-bottom:1px solid #e3e3e3; margin-bottom:10px;padding:12px 0 0 12px;">
    <h4>
        <img src="https://www.amitbera.com/amitbera-com.jpg" alt="Amit Bera" style="height: 60px;"/><br>
        <div style="padding-left: 11px;">
            <p>
                <strong style="color:#EA7601;">
                    Cms / Custom /Static Links To Menu v <?= /* @noEscape */ $block->getModuleVersion() ?> by
                </strong>
                <a target="_blank" href="https://www.amitbera.com" title="Amit Bera Store - Free / Premium Magento Extensions,  Themes &amp; Services">
                    <strong>Amit Bera</strong>
                </a>
            </p>
            <p>
                <?= /* @noEscape */ __('Need help? See our') ?>
                <a href="https://www.amitbera.com" target="_blank" title="Amit Bera Blog - Tutorials, Tips &amp; Tricks for Magento, PHP, MySQL &amp; DevOps">
                    <?= /* @noEscape */ __('Blog') ?>
                </a>
                <?= /* @noEscape */ __(' or contact us via') ?>
                <a href="https://www.amitbera.com/contact" target="_blank" title="Amit Bera - Contact Us"><?= /* @noEscape */ __('form') ?></a>.
                <?= /* @noEscape */ __(' Got feedback? ') ?>
                <a href="mailto:dev.amitbera@gmail.com?Subject=M2 Cms links Version <?= $block->escapeHtml($block->getModuleVersion()) ?> for <?= $block->escapeHtml($block->getMageVersion()) ?>">
                    <?= /* @noEscape */ __('Email us') ?>
                </a>
            </p>


            <h3>
                <a style="padding: 6px 30px 6px 30px;background-color:#EB5202; color:white; font-weight: bold;"
                   href="https://www.amitbera.com/contact" title="Amit Bera - Contact Us" target="_blank">
                    <?= /* @noEscape */ __('Need Support? Contact us') ?>
                </a>
            </h3>
        </div>
    </h4>
</div>